### ISSUE TITLE
Investigate why the update to karma-qunit@2 & qunit breaks tests

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/videojs-contrib-eme#45]
These tests fail when updating `karma-qunit` to version 2 and installing `qunit` rather than `qunitjs`. Which is require for v2 of `karma-qunit` and `qunitjs` is no longer getting version updates.

```
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) videojs-contrib-eme eme accepts a license URL as an option FAILED
	keySession.generateRequest is not a function
	TypeError: keySession.generateRequest is not a function
	    at makeNewRequest (test/eme.test.js:25:21342)
	    at addSession (test/eme.test.js:25:21973)
	    at test/eme.test.js:25:29152

HeadlessChrome 0.0.0 (Mac OS X 10.12.6) videojs-contrib-eme eme accepts a license URL as property FAILED
	keySession.generateRequest is not a function
	TypeError: keySession.generateRequest is not a function
	    at makeNewRequest (test/eme.test.js:25:21342)
	    at addSession (test/eme.test.js:25:21973)
	    at test/eme.test.js:25:29152
```

**Comment by forbesjo** [comment]
Closing since we use the vjs karma tool now
